### ISSUE TITLE
Spring Boot Question

### ISSUE THREAD

**Issue by Rapter1990** [sanjaypakale/spring-boot-crud-hibernate#1]
I'd like to say that it's a great example. What I just want to ask is to share some code snippets in Postman part like what json code we write in the process of adding entity.

**Comment by sanjaypakale** [comment]
Thank you for your words. 
You can send a json code in the http body. below is example.
{
    "name": "tom",
    "gender": "male",
    "department": "IT",
    "dob": "1992-11-25"
}

![employee_save](https://user-images.githubusercontent.com/16380257/79677503-c174d080-820f-11ea-95a3-6f8f00e2b03f.PNG)

**Comment by Rapter1990** [comment]
Thank you for your post. I looked through entity class and dob was defined as Date but you wrote it as String in Postman. Can you explain the process of Date in detail if you don't mind.
